ekf_localization_odom:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom  # The frame representing your odometry data
    base_link_frame: base_link  # The base link frame of your robot
    world_frame: odom   # Using odom as the reference frame for localization, no map frame needed

    # Odometry input 
    odom0: /diff_cont/odom
    odom0_config: [false, false, false,       # x, y, z (position)
                       false, false, false,      # roll, pitch, yaw (orientation)
                       true, false, false,      # vx, vy, vz (linear velocity)
                       false, false, true,      # vroll, vpitch, vyaw (angular velocities)
                       false, false, false]     # ax, ay, az (linear acceleration)
    odometry0_differential: false
    # odometry0_queue_size: 10

    # IMU input
    imu0: /imu_plugin/out  # Your IMU topic
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  true, false, false]
    imu0_differential: false
    # imu0_queue_size: 50

    # Optional smoothing for lagged data
    # smooth_lagged_data: true
    # history_length: 5.0
