twist_mux:
  ros__parameters:
    topics:
      nav2:
        topic   : cmd_vel 
        timeout : 0.5
        priority: 10
      teleop:
        topic   : /cmd_vel_teleop   # Ensure this is the teleop topic
        timeout : 0.5
        priority: 100       # Give it a higher priority

